star/private/star_utils.f90

`get_phot_info` can ultimately return values from either the outermost meshpoint, interpolation inside the model, or the innermost meshpoint. The first and last option include a catch
```f90
L = max(1d0, s% L(1)) ! don't use negative L(1)
```
but the second option (interpolation) did not, which caused an FPE error in `T_tau_gradr`. This PR fixes that by adding the same catch before returning after interpolation. The FPE situation is [no worse](https://testhub.mesastar.org/whb%2Fnegative-L-FPE/commits/89da512) and a full run of the test suite is [passing](https://testhub.mesastar.org/whb%2Fnegative-L-FPE/commits/e05468d).

Catch negative luminosity in `star_utils:get_phot_info`

---

star/defaults/controls.defaults
star/defaults/controls_dev.defaults
star/private/alloc.f90
star/private/brunt.f90
star/private/evolve.f90
star/private/hydro_momentum.f90
star/private/mesh_adjust.f90
star/private/star_utils.f90
star/private/struct_burn_mix.f90
star_data/public/star_data_step_work.inc

The MESA option use_mass_corrections allows the user to enable a set
of corrections that distinguish between baryonic and gravitational
mass.  The mass (m) and density (rho) in MESA are baryonic.  The
corrections are due to the composition-dependent mass excess, which is
provided for each cell by chem_lib as mass_correction.  The
gravitational (or inertial) mass of a cell is then given by
dm(k)*mass_correction(k) and the gravitational mass (m_grav) is
obtained by cumulatively summing the per-cell values from the center
to the surface.
The key corrections are as follows:
The momentum equation concerns the inertial mass, so mass corrections
should modify the dm present in this equation.  As was already being
done, the gravitational acceleration should use m_grav.
The Brunt-Vaisala frequency …

Rework approach to distinguish baryonic and gravitational mass

---

binary/private/binary_ctrls_io.f90
binary/private/binary_job_ctrls_io.f90
binary/public/binary_lib.f90
eos/private/eos_ctrls_io.f90
eos/public/eos_lib.f90
kap/private/kap_ctrls_io.f90
kap/public/kap_lib.f90
star/private/ctrls_io.f90
star/private/pgstar_ctrls_io.f90
star/private/star_job_ctrls_io.f90
star/public/star_lib.f90

This adds a get and set subroutine for each namelist
(eos, kap, controls, star_job, binary_controls, and binary_job) though pgstar namelists are not supported,
that allows setting a variable as a string, thus:
call star_get_control_namelist(id,'mesh_delta_coeff',var,ierr)
or
call star_set_control_namelist(id,'mesh_delta_coeff','1.5',ierr)
This means any code that interfaces with mesa and its modules no longer
needs to understand what a namelist is or the how to understand the various
*_info derived types (good luck any one attempting to interface with star_type).

Add support for setting namelists as strings.

---

star/private/rotation_mix_info.f90
star/private/star_utils.f90

Removed some unused functions from `star_utils`:
- `store_r_or_lnR_in_xh`
- `find_tau_phot`
- `get_r_phot`
- `get_phot_kap`
- `rsi_div_rsimelt`
- `median_smoothing`
- `arrived_main_seq`
- `set_max_QHSE_time_scale`
- `get_grada_face_val`
- `get_grav_face`
- `get_QQ_face`
- `store_w_in_xh`
- `store_etrb_in_xh`
- `store_T_or_lnT_in_xh`
- `store_rho_or_lnd_in_xh`
Please comment if you want any of these to stay.

Remove unused functions

---

star/defaults/controls.defaults
star/private/adjust_mass.f90
star/private/adjust_mesh_split_merge.f90
star/private/ctrls_io.f90
star/private/hydro_rotation.f90
star/private/mesh_adjust.f90
star/private/star_utils.f90
star/test_suite/dev_high_rot_darkening/inlist_high_rot_darkening
star/test_suite/dev_ppisn/src/run_star_extras.f90
star_data/private/star_controls.inc

Suggested by @orlox in #331, as we were only keeping the old prescription around in case the new one ran into trouble. Given that it's been two years since the change (MESA 11701) it may be time to remove it.
@orlox Could you take a look and make sure I didn't mess anything up in the process? I'll wait for you to sign off and for testhub to clear before merging.

Removes old prescription for calculating moment of inertia (equivalent to setting `fitted_fp_ft_i_rot = .true.`).

---

net/public/net_lib.f90
star/defaults/profile_columns.list
star/other/other_net_get.f90
star/rsp2_utils/profile_columns.list
star_data/public/star_data_def.inc
star_data/public/star_data_step_work.inc

While trying to work out which way to [fix](67e15faf84d52bcb4c303aceaf261b8a014aac8a) an inconsistency in how `burning_regions` were determined, I found the docs quite confusing about which variables already include neutrino losses. The confusing statements are usually something along the lines of "subtracting" neutrino losses, where I was confused about whether that meant the reaction neutrino losses were a *negative* number being added back in (by subtracting the negative variable) or a *positive* number being accounted for where they hadn't already.
This PR is to fix these. I'm open to changes on the wording or anyone adding other potentially confusing occurrences.
I'm tagging @rjfarmer and @fxt as the owners of `neu`, `net` and `rates`, and therefore the people who probably have the …

Avoiding ambiguity in what it means to "subtract" neutrino losses

---

docs/source/changelog.rst

This PR would add the original release notes for releases [10398](https://lists.mesastar.org/pipermail/mesa-users/2018-March/008812.html), [11532](https://lists.mesastar.org/pipermail/mesa-users/2019-March/009842.html), [11554](https://lists.mesastar.org/pipermail/mesa-users/2019-March/009905.html) and [12115](https://lists.mesastar.org/pipermail/mesa-users/2019-September/010470.html) from the MESA users list to the change log in the documentation, where they might be easier to find. This was prompted by [an issue](https://lists.mesastar.org/pipermail/mesa-users/2021-November/013356.html) on the mailing list that was partly about changes from 10398 to 15140.
I've lightly edited the original content but there remain some links that don't make sense. I'm in favour of merging this and we can …

Release notes for older releases (10398, 11532, 11554 & 12115)

---

star/defaults/controls.defaults
star/private/adjust_mesh.f90
star/private/alloc.f90
star/private/ctrls_io.f90
star/private/evolve.f90
star/private/evolve_support.f90
star/private/hydro_vars.f90
star/private/init.f90
star/private/photo_in.f90
star/private/photo_out.f90
star/private/read_model.f90
star/private/relax.f90
star/private/rotation_mix_info.f90
star/private/struct_burn_mix.f90
star/test_suite/15M_dynamo/src/run_star_extras.f90
star/test_suite/magnetic_braking/src/run_star_extras.f90
star_data/private/star_controls.inc
star_data/public/star_data_step_input.inc
star_data/public/star_data_step_work.inc

These changes do two things:
- Include the effect of the Brunt on the calculation of rotational diffusion coefficients when using the Schwarzschild criterion. This is the problem Radec reported with large differences in rotational mixing between Ledoux and Schwarzschild.
- Restore time smoothing of the ST diffusion coefficients. This solves Mathieu's issue.
Attached is a comparison of a model of a 30 Msun star at 0.1 critical (adapted from Mathieu's example) ran with 15140 and HEAD of the pm/rotation_fixes branch. I also run the simulations with and without time smoothing, and it gives me consistent results. To do the time smoothing one needs to interpolate the diffusion coefficient from the old mesh in the previous step, I wrote down a simple linear interpolant in rotation_mix_info for …

Fixes for rotation (Radec's and Mathieu's issues)

---

.github/workflows/build-linux.yml

This adds a GitHub Action that tests that MESA compiles with the SDK under the latest version of Ubuntu. Most of the work to set this up was actually done by @rjfarmer, who tried to set something up to integrate with TestHub. If the TestHub integration starts working, we should disable this.
Note that this is *not* the same as installing MESA on a clean install of Ubuntu because the GitHub runner environment has other software installed too.
Comments welcome, and feel free to tweak the script directly. There are also GitHub runners available for Mac OS 11 and 10.5 but I leave that to a Mac expert.

Create basic build action for Linux

---

docs/source/using_mesa/inlist_example
docs/source/using_mesa/running.rst

In getting started with MESA, I noticed that in the loading a model section of the running mesa documentation, an outdated option syntax was used. I believe I've replaced it with the correct option.

fixing outdated energy equation option in running MESA documentation

---

docs/source/using_mesa/running.rst

I spent a few hours trying to debug starting the inlist for starting from an existing model only to finally discover the issue was that my file didn't end with a blank line (I'm sure this is obvious to regular fortran users). The inlist modeled in the documentation doesn't include this return and I'm not sure how to get the RST to render it, so I added a sentence to try to head off this issue.

adding sentence about ending inlist file with carriage return

---

eos/private/skye_coulomb.f90
eos/private/skye_coulomb_liquid.f90
eos/private/skye_coulomb_solid.f90
math/make/makefile_base
math/public/math_def.f90
math/public/math_lib_crmath.f90
math/public/math_lib_intrinsic.f90
math/public/precompute_zs.inc
rates/private/screen_chugunov.f90
rates/public/rates_lib.f90

Many places in the EOS (and screening) compute powers of the charge Z
but given there is only a small number of Z's we can just precompute
the terms (which are saved into a new math_def module).
This saves about 5% runtime on a test case I ran.

Pre compute some powers of (integer) Z

---

atm/private/atm_t_tau_uniform.f90
atm/private/atm_t_tau_varying.f90
docs/source/test_suite.rst
docs/source/test_suite/check_pulse_atm.rst
star/private/atm_support.f90
star/private/pulse_cafein.f90
star/private/pulse_fgong.f90
star/private/pulse_gyre.f90
star/private/pulse_osc.f90
star/private/pulse_saio.f90
star/public/star_lib.f90
star/test_suite/check_pulse_atm/README.rst
star/test_suite/check_pulse_atm/ck
star/test_suite/check_pulse_atm/clean
star/test_suite/check_pulse_atm/inlist_check_pulse_atm
star/test_suite/check_pulse_atm/inlist_check_pulse_atm_header
star/test_suite/check_pulse_atm/make/makefile
star/test_suite/check_pulse_atm/mk
star/test_suite/check_pulse_atm/re
star/test_suite/check_pulse_atm/rn
star/test_suite/check_pulse_atm/rn1
star/test_suite/check_pulse_atm/src/run.f90
star/test_suite/check_pulse_atm/src/run_star_extras.f90
star/test_suite/do1_test_source

Some time ago, `Teff` changed from an output from `atm` to an input to `atm`, because `atm` doesn't necessarily know where the photosphere of a star is. Many of these changes weren't reflected in the `build_atm` routines that are used to compute the atmospheric structure that's appended to the pulsation formats (e.g. FGONG), as noted in #375. This PR fixes the immediate issues and completes the transition. It also adds a new test case `check_pulse_atm` that writes the FGONG file, then reads it back in and checks that the atmosphere structure matches the selected T(τ) relation.
In the future I'll extend the test to check other formats, too, but for now it only checks FGONG.
I'll leave this open for a few days for comments.

Fix `build_atm` to take Teff as input

---

astero/defaults/astero_search.defaults
astero/private/adipls_support.f90
astero/private/astero_run_support.f90
astero/private/extras_support.f90
astero/private/gyre_support.f90
astero/public/astero_def.f90
astero/test_suite/do1_test_source
astero/test_suite/fast_simplex/inlist_astero_search_controls
astero/test_suite/fast_simplex/rn
astero/test_suite/fast_simplex/src/run_star_extras.f90
docs/source/changelog.rst

As [mentioned](https://github.com/MESAHub/mesa/pull/367#pullrequestreview-874479268) in PR #367, users currently have to create any folder for `astero` results themselves. This PR adds a new option `astero_results_directory` (by analogy with `log_directory` in `star`), which means MESA can create the relevant folder itself while the code runs.
This only affects (and was motivated by) `fast_simplex`, which is passing.

Create `astero_results_directory` option

---

star/defaults/history_columns.list
star/defaults/profile_columns.list
star/private/history.f90
star/private/history_specs.f90
star/private/profile.f90
star/private/profile_getval.f90

Adds the capability to output either all the raw rates from the current net, or specifically chosen ones, as specified in the history and profile columns lists. 
One can add `add_raw_rates` to either file to get all of the rates -- either zone by zone (added to `profile_columns.list`) or summed over all the zones (`history_columns.list`). Alternatively, one can specify individual rates, such as `raw_rate r_h1_h1_ec_h2`, to get only the information for that rate. 
If one requests a rate that does not exist (e.g. `r_h12_h1_wk_h2`), then it fails while reading with the error `bad rate name: r_h12_h1_wk_h2`. 
It furthermore adds the boilerplate code to set up similar outputs for `add_screened_rates`, `add_eps_nuc_rates`, `add_eps_neu_rates`, and their individual counterparts. However, the …

Add raw rates to history and profile file outputs 

---

astero/defaults/astero_search.defaults
astero/private/astero_run_support.f90
astero/public/astero_def.f90
docs/source/changelog.rst

This PR changes `astero`'s results files to match profiles and histories, which includes adding options
```f90
astero_results_dbl_format = '(1pes26.16)'
astero_results_int_format = '(i26)'
astero_results_txt_format = '(a26)'
```
to mimic `star_{profile,history}_{dbl,int,txt}_format` (although I've chosen shorter defaults) and adding some of the metadata included in profiles and histories.
E.g., whereas the old format was
```
87  samples
sample                      chi2                      mass                    init_Y                  init_FeH                     alpha                      f_ov ...
48    1.1644430477133496D+02    1.2679054916867951D+00    2.6789933811428168D-01    1.4110372493129281D-01    2.0063468653270946D+00    0.0000000000000000D+00 ...
39    1.1800399138147311D+02 …
```

Update astero results format to match profiles and histories

---

rates/private/raw_rates.f90

When users failed to add the number of lines for the file, we would
infinitely loop and never exit.
Fixes #413

Fix error handling in custom rates

---

astero/test_suite/astero_adipls/src/run_star_extras.f90
astero/test_suite/astero_gyre/src/run_star_extras.f90
astero/test_suite/example_astero/src/run_star_extras.f90
astero/test_suite/fast_from_file/src/run_star_extras.f90
astero/test_suite/fast_newuoa/src/run_star_extras.f90
astero/test_suite/fast_scan_grid/src/run_star_extras.f90
astero/test_suite/fast_simplex/src/run_star_extras.f90
astero/test_suite/surface_effects/src/run_star_extras.f90
star/public/star_lib.f90
star/test_suite/zams_to_cc_80/src/run_star_extras.f90

I recently made use of `star_lib`'s `star_get_history_output` function, which has the call signature
```f90
real(dp) function star_get_history_output(s, name)
```
If it fails to find a history column with the requested `name`, it returns `-HUGE(0.0d0)`. This PR changes the call signature to
```f90
real(dp) function star_get_history_output(s, name, ierr)
```
where `ierr` is optional and, if included, returns `ierr = 1` if the column wasn't found so that the caller can more easily handle a failure.
This isn't the only procedure where I can't see a robust way of handling errors. Others that caught my eye are
```f90
real(dp) function star_get_history_output_by_id(id, name) ! closely related
real(dp) function star_get_profile_output(s,name,k)
real(dp) function star_get_profile_output_by_id(id, …
```

Add `ierr` output to `star_lib:star_get_history_output` (and maybe similar procedures)

---

star/defaults/controls.defaults
star/defaults/history_columns.list
star/private/ctrls_io.f90
star/private/evolve.f90
star/test_suite/rsp_Type_II_Cepheid/src/run_star_extras.f90
star_data/private/star_controls.inc

It seems misleading to allow positive and negative energy errors from subsequent steps to cancel out when adding up the cumulative energy error, so I propose that we always add the absolute value of energy error from each step. This helps some plots I'm working on for the MESA VI energy section make more sense.
@rsmolec I had to relax the tolerance on the `rel_run_E_err` in the run_star_extras for `rsp_Type_II_Cepheid` for it to pass with this new calculation of cumulative energy error.

Make cumulative energy error add absolute value of error from each step

---

binary/private/binary_evolve.f90
binary/private/binary_photos.f90
binary/private/binary_timestep.f90
binary/public/binary_data.inc

the binary timestep control b_fm might be unjustly tripped if the donor was switched.
If the donor is switched at the start of the step, b% env_old is not updated to reflect the envelope mass of the new donor.
made b% env an array so both stars can have their envelope stored

Fix to b% fm to account for the donor switching during the step

---

kap/private/condint.f90
kap/private/kap_eval.f90

Fixes a bug discovered by the students at MESA Summer School 2022.
331b515fe3e7d34be1453c81fac8b2f6ad07e95c introduced a bug by changing where the conversion from thermal conductivity to conductive opacity occurs. This change missed some `zlog` edge cases because they included `return` statements that caused the conversion at the end to be skipped. This manifested as `NaN` values for the `kap` derivatives because they never got set, and the returned opacity was also wrong (though not `NaN`). These `NaN`s in the derivatives propagated through to the overall opacity derivatives even when conductive opacities should be irrelevant.
The most relevant edge case where this occurs is for a pure hydrogen composition, though in principle it could also occur for a very high `zbar` (>60).

Fix for conductive opacity edge cases

---

math/public/math_lib_intrinsic.f90

When compiling release `r22.05.1` or the current `main` with `USE_CRMATH = NO`, I'm getting this error.
```
COMPILE_CMD ../public/math_def.f90
COMPILE_CMD ../public/math_lib_intrinsic.f90
precompute_zs.inc:8:10:
Error: Unclassifiable statement at (1)
precompute_zs.inc:5:33:
Error: Symbol 'max_precomp_ints' at (1) has no IMPLICIT type
```
I think the reason is that `math_lib_intrinsic.f90` does not have a `use math_def` statement. The alternative file `math_lib_crmath.f90` does load this module.
This PR fixes compilation with `USE_CRMATH = NO`.

fix compiling with `USE_CRMATH = NO`

---

binary/defaults/binary_controls.defaults
binary/private/binary_ctrls_io.f90
binary/private/binary_jdot.f90
binary/public/binary_controls.inc

qrad_core and jdot_mb_max_qrad_core are misleading variable names since check_jdot_mb_conditions (binary/private/binary_jdot.f90) is actually checking that the convective core is not too large (ie that there actually is a radiative core). The documentation is also updated to reflect what the check_jdot_mb_conditions subroutine is actually doing.

Change in check_jdot_mb_conditions and binary_controls

---

star/job/run_star_support.f90

When using r15140 with linux SDK 20.12.1 to run binary models, I unfortunately noticed no history or profiles of the stars were saved. I tracked the issue down to `run_star_support: after_step_loop`, where `star_finish_step` was not called since `result = -470533012` (or any other number that happened to be in that memory location) at that point. 
Newer compilers (such as the macOS SDK 22.6.2) seem to implicitly put `result = 0 (== keep_going)`, which avoids this issue, but still, if `result == terminate` upon invocation of `after_step_loop`, this value is not considered because of the `intent(out)`
simply changing the intent to `inout` avoids problems on any compiler, and lets `after_step_loop` take in the `result` value you give it.
Weird that this issue did not turn up earlier, SDK …

fix to after_step_loop so incoming result value is considered

---

star/private/winds.f90

fix for issue #456
Wind mass loss rate is determined by iron opacity, unlikely to change during the evolution. The surface Z can change (because of changes in H, He, C, N, O) but this usually does not change the iron group elements, and should not affect the line-driven wind mass loss rate (see e.g., [Tramper et al.
2016](https://ui.adsabs.harvard.edu/abs/2016ApJ...833..133T/abstract), [Sabhahit et al. 22](https://arxiv.org/abs/2205.09125) and references therein).
If Zbase is set (for type 2 opacities), use that fixed constant value in the wind routine. If Zbase is not set, fall back on the previous behavior.

use Z = Zbase in wind mass loss routines

---

atm/private/atm_t_tau_relations.f90
star/private/create_initial_model.f90
star/private/init.f90
star/private/pgstar_production.f90
star/private/pre_ms_model.f90

When an initial model is constructed with `initial_y < 0`, a basic enrichment law `Y=0.24 + 2Z` is invoked:
https://github.com/MESAHub/mesa/blob/68644ccd15db719d33c62ad03754135cbbdd2920/star/defaults/controls.defaults#L59-L73
The enrichment law doesn't carry through to the FGONG or OSC pulsation formats, which @AntoNoll flagged in #465. On investigating, this enrichment law was being invoked in at least three places. This PR refactors all of this by changing the value of the control `s% initial_y` itself to use the enrichment law, so that subsequent routines only see that (positive) value.
`s% initial_y` is only re-assigned just before an initial model is constructed. I don't often start from existing models or photos. I'm not sure if this might cause unexpected behaviour but I assume …

Refactor basic enrichment law (Y=0.24+2Z) for initial models with `initial_y = -1`

---

docs/source/auto_diff/overview.rst

Following [a question on MESA users](https://lists.mesastar.org/pipermail/mesa-users/2022-December/014183.html), I noticed that [the `auto_diff` overview](https://docs.mesastar.org/en/release-r22.11.1/auto_diff/overview.html) doesn't describe the indices of the `auto_diff_real_star_order1` type. This change is mainly to point to where users can find them, without adding them directly to the docs where they're at risk of falling out of sync.
I'm doing this as a PR so that anyone can comment on/commit further changes to the `auto_diff` help. I've used `auto_diff` relatively little myself so am open to those with more experience correcting/improving what I've written.
I had a quick look in the test suite for cases that made interesting use of the `auto_diff` type. `starspots` and `ppisn` do …

Tweak `auto_diff` overview to point to index values for `auto_diff_real_star_order1`

---

CONTRIBUTING.rst
docs/source/developing.rst
docs/source/developing/collaboration.rst
docs/source/developing/new_developers.rst

Adds new developer document, as voted on by the developers.
I'll leave this here for a bit for any comments on the RST formatting and integration with the other docs

[ci skip] Add new developer document to the docs

---

binary/defaults/binary_controls.defaults
binary/private/binary_ctrls_io.f90
binary/private/binary_wind.f90
binary/public/binary_controls.inc
binary/test_suite/wind_fed_bhhmxb/inlist_project

Made the trivial fix to #433 by changing the orbital velocity.
I also added the functionality to change the wind_beta value since the default 1/8 is only appropriate for cool supergiants.

Fix+enhance wind accretion

---

docs/source/about.rst
docs/source/developing/collaboration.rst
docs/source/developing/infrastructure.rst
docs/source/developing/new_developers.rst

This is mostly focused on bringing some other parts of the documentation on the website in line with the new developer onboarding document. This removes some outdated language about the MAC/MTC playing the primary role in onboarding new developers.
It also contains some cosmetic changes to the onboarding document itself, but nothing that changes the meaning of the document. A few miscellaneous updates to infrastructure documentation as well.

Updates to some documentation about the structure of MESA Developers

---

mtx/public/mtx_solve_routines.inc

The idea is to allow the compiler to have a better guess at what does/not change in a loop. By pulling out some of these array access the compiler can see things don't change.
Testing against split_burn_big_net didn't show any improvement (or worsening) but using the MESA's one zone burner in a standalone mode showed 30% speed up. While also showing no difference in final results. This seems to mostly benefit when running big nets ( few hundred isos), split_burn_big_net only uses 80 isotopes.

Speed up getf2

---

binary/defaults/binary_controls.defaults
binary/private/binary_ctrls_io.f90
binary/private/binary_wind.f90
binary/public/binary_controls.inc
binary/test_suite/wind_fed_bhhmxb/inlist_project

From testing branch onto `main` after merging #476 from @matthiasfabry.
Original message:
> Made the trivial fix to https://github.com/MESAHub/mesa/issues/433 by changing the orbital velocity.
I also added the functionality to change the wind_beta value since the default 1/8 is only appropriate for cool supergiants.

Fix wind accretion

---

star/private/struct_burn_mix.f90
star_data/private/star_job_controls_params.inc

restoring eps_nuc_neu to zones undergoing operator split burn. This fixes the history output for 'eps_nuc_neu_total', 'log_Lneu', and 'log_Lneu_nuc'

restoring eps_nuc_neu to split burn zones

---

star/private/hydro_alpha_rti_eqns.f90
star/test_suite/ccsn_IIp/inlist_end_infall
star/test_suite/ccsn_IIp/inlist_infall

RTI has been broken for ~2 years since 181c9fac as we had a check for rho < 1d99 and if true we would turn off the RTI source term (and thats of course always true).

Enable RTI source terms

---

star/private/history.f90
star/private/profile_getval.f90
star_data/public/star_data_step_work.inc

eps_nuc as reported by net/ already contains the eps_nuc_neu (nuclear neutrino) losses. Thus we should not subtract them again.
Fixes #493

Fix eps_nuc output

---

kap/private/condint.f90
kap/private/kap_eval.f90
kap/public/kap_lib.f90
star/private/kap_support.f90
star/private/micro.f90

This cleans up some of the behavior at the surface of models when `op_mono_method = 'mombarg'`.
This will fall back to the regular opacity routines for the atmosphere rather than OP Mono in this case, since the approximations from the `'mombarg'` routines seem to cause convergence issues in the atmosphere.
The original version of the `'mombarg'` routines actually did something similar to this by accident due to a bug that yielded `NaN` values in the atmosphere and forced falling back from OP Mono to regular opacities anyway. A fix to conductive opacities in #438 caused this behavior to go away and significantly slowed down the example MESA VI work directory as of release `r22.11.1`.
This PR yields a significant speedup for the MESA VI example work directory relative to `r22.11.1`, and is …

Speed up OP Mono Mombarg Routines

---

gyre/build_and_test
gyre/build_and_test_parallel
gyre/gyre-6.0.tar.gz
gyre/gyre-7.0.tar.gz
gyre/public/gyre_lib_stub.f
star/job/gyre_in_mesa_extras_finish_step.inc
star/job/gyre_in_mesa_extras_set_velocities.inc
star/test_suite/rsp_gyre/src/run_star_extras.f90

A new version of GYRE ([v7.0](https://github.com/rhdtownsend/gyre/releases/tag/v7.0)) was released Jan 18. This updates MESA by replacing the bundled archive and updating one API change (`md%n_k` → `md%n`) in a few places. I manually cross-checked the results of all the `gyre_in_mesa` tests in `star` as well as `astero_gyre` in `astero` and the only changes were around 10⁻⁷ level changes in some growth rates.
I won't merge this without approval from @rhdtownsend. There's no particular rush but we should merge before the next release.

Update GYRE to v7.0

---

math/public/math_lib_crmath.f90
math/public/math_lib_intrinsic.f90

addresses #510.
All tests on [Cannon](https://testhub.mesastar.org/change_safe_logs/commits/3529123) are passing, so I'd propose to implement this change into main. Although we'd probably want to test also on other systems too, since these low level routines could be machine/architecture/compiler dependent.

change safe_logs test from IEEE_NORMAL to IEEE_FINITE

---

binary/public/binary_lib.f90

I've had a request to make the binary_tides.f90 function k_div_T made publically available. Comments on the API?

Add public interface for k_div_T

---

star/defaults/controls.defaults
star/private/alloc.f90
star/private/ctrls_io.f90
star/private/hydro_energy.f90
star/private/hydro_momentum.f90
star/test/test_output
star_data/private/star_controls.inc
star_data/public/star_data_step_work.inc

In a previous version of mesa (r15140), there existed controls to apply a velocity drag to the outer envelope of a model. This drag functions by converting kinetic energy into heat. This control was useful for preventing instabilities in the envelope from accelerating material at glorious speeds, and is also useful in the preventing radial pulsations and other instabilities that developed near the surface of a model. I've found this control particularly useful for getting 1-7 Msun stars through the thermal-pulsing AGB, and for generating smooth hr tracks in Massive stars from Carbon burning on. I've had success taking massive stars from 15-150 Msun to cc (infall ~ 300 km/s) with this this control.
It should be noted that if you run the drag factor 'drag_coefficient = ' at 1d0 too long, …

Reintroducing velocity drag for v flag

---

star/private/relax.f90
star/test_suite/relax_composition_j_entropy/inlist_start_relax_composition_j_entropy
star_data/public/star_data_step_work.inc

I gave a https://github.com/MESAHub/mesa/issues/534#issue-1702284534 a crack. Let me know if this looks correct? 
Line 845 might be too long? Didn't see any issues in the other relaxation routines. Will double check.

add star_pointer initial_star_age to track when relaxation begins

---

star/private/relax.f90
star/test_suite/relax_composition_j_entropy/inlist_start_relax_composition_j_entropy

The problem with the relax routines is that they assume the star_age is 0, so this fixes things by forcing that to be true and then restoring the star_age afterwards. Note we don't want to do any subtracting of an initial age as there can be precision loss when star_age is large as the entropy and angular momentum routines assume dt << 1s.

Fix issues with entropy relaxtaion when star_age>0 (#536)

---

astero/test_suite/astero_adipls/src/run_star_extras.f90
star/test_suite/carbon_kh/src/run_star_extras.f90
utils/makefile_header
utils/makefile_header_non_mesasdk

Fixes #537, where @mjoyceGR showed that a bad namelist item after an array leads to an error message that points to the array item, rather than the bad namelist item. Following up on the [associated GCC bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109897), using the `-std=f2008` flag seems to fix this behaviour. This PR just adds that flag in a place that fixes the error. There are still parts of `star` that are compiled without the flag but that doesn't seem to matter.
This led to small changes in `carbon_kh` and `astero_adipls`, which apparently didn't already conform the the Fortran 2008 standard and [failed to compile](https://testhub.mesastar.org/whb%2Fstar-work-std-f2008/commits/e0e56f4).
The test suite is now [passing](https://testhub.mesastar.org/whb%2Fstar-work-std-f20 …

Add `-std=f2008` flag when compiling `work` folders

---

docs/source/eos/overview.rst
eos/private/ideal.f90

Ideal EOS is currently including the full ionization energy as part of the internal energy, which is inconsistent with its assumption that the matter is fully neutral. I suspect this is just an artifact of porting ideal over from skye_ideal, which does assume full ionization.

Fix ideal neutral energy

---

binary/other/mod_other_binary_extras.f90

@rjfarmer's perfectly [reasonable change](https://github.com/MESAHub/mesa/pull/550) of moving the `use` statements into the `other` procedures inexplicably broke the `ifort` build by introducing errors about the variable `names` being given conflicting attributes:
```
...
../other/mod_other_binary_extras.f90(135): error #6401: The attributes of this name conflict with those made accessible by a USE statement.   [NAMES]
character (len=maxlen_binary_history_column_name) :: names(n)
--------------------------------------------------------------^
../other/mod_other_binary_extras.f90(130): warning #6717: This name has not been given an explicit type.   [NAMES]
subroutine null_data_for_extra_binary_history_columns(binary_id, n, names, vals, ierr) …
```

Fix `ifort` build by renaming supposedly conflicting variable

---

docs/source/changelog.rst
star/private/history.f90

We would attempt to detect whether a extra history value was meant to be an int or a float. But this was error prone with very large values. Instead just treat everything as a float (given users can only provide values in floats anyway this should not change peoples results).
Closes #354

Stop trying to convert history values to ints

---

data/net_data/nets/README.rst

Add in `data/net_data/nets/README.rst` text to describe the use of the executable `show_rates` to visualize the temperature dependence of rates used by MESA from the cache. Based on in person discussions with @rjfarmer

document `show_rates`

---

docs/source/changelog.rst
star/private/star_solver.f90
star/private/struct_burn_mix.f90
star_data/public/star_data_step_work.inc

Conventionally we have been limited in the size of a mesa problem
(zones * isos) by the size of the solver_work arrays, which was
~ (zones * isos* isos* A). Where A is a constant based on the fact that the
solver work arrays contain multiple sub-arrays that get split apart
into the different arrays needed. A was about ~10.
By splitting the work array up into its consistent parts each individual
array can now reach SIGNED_INT_MAX (2^31). So we should scale closer to
the maximum problem size being max_isos = sqrt(2^31 / zones). For
1000 zones that is potentially ~1400 isos. Whether we can actually hit
that depends on whether there are other arrays that scale worse than
isos * isos * zones.
Most of the changes are just the code of do_solver being indented. I did this
as I moved the code to a …

Increase maximum nuclear network size

---

.github/workflows/build-linux.yml

The CI has started failing because it runs out of space before the build can complete. This appears to be a common enough issue that a common workaround, compiled into [this action](https://github.com/marketplace/actions/free-disk-space-ubuntu) (for example), is to delete/uninstall a bunch of unused software that's included on the GitHub runner.

Delete unused libraries from GitHub runner

---

star/defaults/star_job.defaults

Added documentation to the relax_zfracs and change_zfracs routines to let users know that it does not adjust the initial_zfracs of the model. see https://github.com/MESAHub/mesa/issues/578

add documentation to change and relax z_fracs routine for initial_zfracs

---

star/defaults/pgstar.defaults

These changes:
- Fix some typos in the pgstar documentation
- Fix some formatting for proper display in browser
- Clarify language throughout, removing many references to "this", replacing them with the appropriate explicit variables 
- Reinforce a common documentation format for each window type in pgstar with consistent labelling and ordering
I did not alter any variable names, but did move some around in their respective sections for clarity. 
I mostly opted to use bolded text as opposed to level headings, as the heading levels were not quite clear when output to html and Sphinx seems to not like repeated heading text.

Reformatting of pgstar documentation

---

star/defaults/controls.defaults
star/private/ctrls_io.f90
star/private/phase_separation.f90
star/private/turb_info.f90
star_data/private/star_controls.inc

This is a fairly straightforward extension of the existing C/O phase separation infrastructure to include an option to use the appropriate diagram for O/Ne mixtures in massive WDs.

Add O/Ne Phase Separation Option for Massive WD Crystallization

---

docs/source/changelog.rst
star/defaults/controls.defaults
star/private/hydro_vars.f90
star/test_suite/conductive_flame/README.rst

A first pass at reimplementing The fixed surface options. See https://github.com/MESAHub/mesa/issues/583
I have tested it to be working locally for 'fixed_Tsurf' in the ppisn test case. 
Feel free to clean up any of it. Do we need a test case for this?
Should this be moved into atm_support.f90, or is it alright to live in hydro_vars.f90?

reimplement fixed atm options

---

star/private/timestep.f90

One liner change here. All retries from the hard limit on nuclear burning luminosity from different sources were coming out as
```
retry: lgL hard limit    2651
```
here 2651 is just the model number. This is really uninformative, as it seems to point out the issue is with the `delta_lgL_hard_limit` option. This change makes the error message actually point a user to the right place. With this change the model that threw the error above gives
```
retry: check_lgL_He_change hard limit    2651
```
which lets me identify the hard limit that actually triggered the problem.

Fix an issue with timestep reporting of changes in nuclear burning L

---

binary/defaults/binary_controls.defaults
binary/private/binary_ctrls_io.f90
binary/public/binary_controls.inc
binary/public/binary_def.f90

This is a small quality of life change that adds ```x_{type}_ctrl``` inlist controls to the ```binary``` module mirroring those already present in the ```star_data``` module. This allows users to define system-specific controls in the ```binary_controls``` namelist instead of using the ```controls``` namelist specific to one of the stars. This is simply because sometimes it it would be preferable to put a special control in ```inlist_project``` rather than in ```inlist1``` when it applies to the whole binary system.
These controls can then be used in ```run_binary_extras.f90``` in a similar way to those in the star_data module:
```
some_var = b% s1% x_ctrl(1)   ! star_data
some_var = b% x_ctrl(1)       ! binary
```
The documentation in ```binary_controls.defaults``` has also been mirrored …

added x_{type}_ctrl inlist controls to binary controls

---

net/private/net_approx21.f90

'denomdt' should be 'denomdd'. If the test_suite passes, this should be fine for a merge.

fix bug in photo derivative

---

.github/workflows/build-linux.yml
docs/source/developing/test_suite.rst

GitHub recently [announced](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/) that their standard action runners have been upgraded from 2 cores to [4 cores](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories). This PR mainly makes that change but while I was tweaking the GitHub workflow I tried updating the SDK matrix to include 23.7.3 (and drop 20.12.1) and not delete packages from the Ubuntu image, which is flaky because the package list sometimes changes.

Some tweaks for CI build action: 2→4 cores, MESA SDK 23.7.3 & maybe don't delete packages from Ubuntu image

---

star/private/report.f90

addresses issue #626 by adding a check on the mass coordinate of index `k_min` less than `fe_core_mass` or `he_core_mass` (for `non_fe_core_infall_limit`), where `k_min` is the index of the minimum of the infall velocity. This is intended to prevent numerically meeting the infall velocity stopping condition because of a spike at the surface after the formation of a non-zero fe core.
Also fixes the calculation of `mass_sum` (used to check that enough mass has a sufficient velocity compared to the parameter `fe_core_infall_mass` or `non_fe_core_infall_mass`): previously the loop was adding *mass coordinates* of each shells `s% m(k)`, instead of the shell mass `s% dm(k)`.
Tested on 12M_pre_ms_to_core_collapse and 20M_pre_ms_to_core_collapse in the test suite.
This does not attempt to make …

check that infall velocity is within core

---

star/defaults/controls.defaults
star/private/ctrls_io.f90
star/private/hydro_energy.f90
star/private/hydro_momentum.f90
star_data/private/star_controls.inc

Implements:
1. `use_drag_energy`: boolean to consider the work done by the drag force in the energy equation (default) or not (in which case the drag force only applies to the momentum equation and its work is not calculated in the energy equation). This may be useful since the kinetic energy "appearing" in the models may be a purely numerical artifact, and we don't necessarily want to consider it as a physical source of energy.
2. `velocity_tau_lower_bound`, real upper limit to where velocities are considered, similar to `velocity_q_upper_bound` but hopefully more easy to generalize across different pre-SN stars. Note that when implementing this by hand in `run_star_extras.f90`, even setting very large values (i.e., upper mass coordinate for `v_flag` far inside the photosphere in …

Adds more options for approaching core-collapse

---

docs/source/changelog.rst
star/private/adjust_mesh.f90

#621 reports a segfault/core dump if MESA tries to exceed the maximum allowed number of mesh points `max_allowed_nz`. I won't pretend I fully understand why this happens but here's a partial diagnosis and a fix that appears to work.
To trigger the basic issue, copy a standard work folder and add/change the following controls:
```
&star_job
...
create_pre_main_sequence_model = .false.
...
/
&controls
...
max_allowed_nz = 100
stop_near_zams = .false.
...
/
```
This should immediately crash with a backtrace (on Linux) that contains:
```
Backtrace for this error:
...
#13  0x4bbc67 in __alloc_MOD_star_info_arrays
at ../private/alloc.f90:512
#14  0x4c27d0 in __alloc_MOD_free_arrays
at ../private/alloc.f90:281
#15  0x4c28a4 in __alloc_MOD_free_star_data
at ../private/alloc.f90:235
...
```
I …

Try to prevent core dump if mesh grows larger than `max_allowed_nz`

---

star/private/relax.f90

Thanks to Annachiara Picco, an oversight of mine when implementing the Bjorklund wind mass-loss rates has surfaced. 
During relaxation of the models, the appropriate `scaling factor` was not put to zero, resulting in the model losing mass during relaxation. This is a simple fix to address that.

Turn off Björklund wind in relax routines

---

docs/source/changelog.rst
star/defaults/controls.defaults
star/private/mesh_plan.f90

As [suggested](https://github.com/MESAHub/mesa/issues/621#issuecomment-1959094641) in issue #621, this PR allows users to ignore `max_allowed_nz` by setting it zero or less, in effect allowing the mesh to grow arbitrarily large, and in keeping with many other controls that are ignored when negative. Consensus seems to be that this should *not* be the default, although we may want to increase it from the current default of 8000.
I'm not sure if we want to strictly compare to -1 or perhaps advise users to use that, which would leave us the option of using particular values of `max_allowed_nz` to control meshing behaviour. I think generally we'd want more description controls anyway (e.g. set a string, not a specific integer) but I thought I'd throw the idea out there before users start …

Ignore `max_allowed_nz` if ≤ 0

---

docs/source/changelog.rst
star/defaults/controls.defaults
star/private/mesh_plan.f90

Reverts MESAHub/mesa#642
I tried setting `max_allowed_nz` to both 0 and -1 in the default work directory after building Warrick's branch, and I get 
```
retry: get_T_tau -- L <= 0       1
1   5.479738   3312.725 -21.748047 -21.748047  15.000000  15.000000   0.700000   0.001010   0.280000 -12.926136   1078      1
-5.3010E+00   5.479738   2.521737 -99.000000 -23.145915 -99.000000   0.000000   0.280000   0.009381   0.020000   0.013983      9
5.0000E-06  -5.414988   4.078909 -99.000000 -99.000000  -8.223226   0.000000   0.003447   0.002085   0.020000  0.000E+00         retry
tried to increase number of mesh points beyond max allowed nz          -1
mesh_plan problem
doing mesh_call_number           1
s% model_number           1
0 terminate reason: adjust_mesh_failed
failed in relax num steps …
```

Revert "Ignore `max_allowed_nz` if ≤ 0"

---

docs/requirements.txt
docs/source/conf.py

Adds a quality-of-life feature to make code blocks in the documentation copyable with a single click.

adding copy button to docs

---

jenkins/Dockerfile

`forum` added a python3 dependency to the overall MESA build.
This is missing in the Jenkins (Flatiron) system and mesa fails to compile. E.g. See logs:
https://logs.mesastar.org/15919513ed6156d61b3de2ec101681a3be7624db/Jenkins/build.log
https://jenkins.flatironinstitute.org/job/mesa/job/main/394/execution/node/32/log/
The build is defined by `jenkins/Jenkinsfile` in https://github.com/MESAHub/mesa
which in turn uses `jenkins/Dockerfile` to define the environment.
I am adding the installation of python3 to the Dockerfile

adding python3 for jenkins to get Flatiron Jenkins build compiling again

---

star/private/star_bcyclic.f90
star/private/star_solver.f90

I am using Caliper (https://software.llnl.gov/Caliper/) to profile parts of the code and understand why scaling typically plateaus beyond 12 cores. Some of it has to do with overhead + small simulation size. But I am detecting some unparallelized code
Here, I've changed `!$omp simd` -->  `!$omp parallel do simd`  to ensure loops are not only vectorized but multi-threaded. The scaling is improved and the 2024 MESA summer school day 1 minilab1.1_5M and a couple seconds are shaved off runtime.

adding parallel do simd

---

chem/preprocessor/src/chem_support.f90

The code to preprocess data about the chemical species does not properly handle errors when reading from the mass table. Currently only one element (re203) has an entry in this table that does not contain data. Instead, the mass excess of the previous row is reused. The processed data file included in the repository does not have this issue, so either it was manually corrected or the tool didn't have the bug when it was generated.
This might not be the best solution (maybe the error should be reported in some way, or the data tables updated), but now it is no longer using bogus data.

chem: fix error handling of preprocessor

---

mtx/public/mtx_solve_routines.inc
star/private/star_bcyclic.f90

Removing some unused variables in parallel loops, and improving a couple omp pragma statements for tiny speedup.
To make future progress in parallelizing Mesa, we will need to parallelize the bcyclic solves when the # threads > # blocks
I've highlighted the timings of critical loops here in `star/private/star_bcyclic.f90`:

Minor improvements to parallelization

---

docs/source/using_mesa/building_inlists.rst
star/test_suite/hb_2M/README.rst

`kappa_file_prefix` -> `kap_file_prefix`. I believe the former is not a valid configuration parameter.

Fix typo in documentation

---

docs/source/conf.py

Fix to Readthedocs upcoming deprecation of Sphinx context injection (see [blog post on the deprecation](https://about.readthedocs.com/blog/2024/07/addons-by-default/))

readthedocs sphinx context injection fix

---

docs/source/conf.py

Reverts MESAHub/mesa#699
because it breaks readthedocs build: 
https://readthedocs.org/projects/mesa-doc/builds/25214806/

Revert "readthedocs sphinx context injection fix"

---

star/defaults/controls.defaults
star/make/makefile_base
star/private/ctrls_io.f90
star/private/hydro_vars.f90
star/private/starspots.f90
star/private/turb_support.f90
star/test_suite/starspots/README.rst
star/test_suite/starspots/inlist_starspots
star/test_suite/starspots/src/run_star_extras.f90
star_data/private/star_controls.inc

starspots is now fully-integrated into MESA and can be used simply in inlists as:
```
do_starspots = .true.
fspot = 0.34d0
xspot = 0.85d0
```
no more need to use a custom run_star_extras.
The `starspots` test_suite problem is updated accordingly

starspots Part 2

---

star/defaults/controls.defaults
star/private/predictive_mix.f90

First stab at addressing gh-issue-[607](https://github.com/MESAHub/mesa/issues/607).
I added an error that gets printed if predictive mixing is called while TDC is on. We could probably flag it earlier so you can't set both controls at the same time on start up? Open to any opinions here, should we disallow users from using these controls together, or just give them a big warning?

Prevent TDC with predictive mixing

---

star/private/create_initial_model.f90

This is a bug in the RK4 solver of `create_initial_model` that has been in Mesa since before the code was added to github. `dP` needs to be `d_P`. The variable `dP` was never defined, and got interpreted as `dp` because Fortran is case-insensitive.
Luckily this bug does not seem to have a large effect in the solver convergence. Tested here: https://testhub.mesastar.org/bugfix%2Fpmocz%2Fquickfixes/commits/1aec194

bugfix dP to d_P in create_initial_model

---

utils/private/utils_c_system.c
utils/private/utils_c_system.h

I noticed some warnings in the C code in the utils module regarding the way strncpy was used. I ended up refactoring the code to make it less complex, and applied a formatter (in a separate commit).

Utils warn cleanup

---

star/defaults/pgstar.defaults

Regarding this mailing list request: https://lists.mesastar.org/pipermail/mesa-users/2024-August/015307.html
Documentation was incorrectly suggesting `pdf` files can be produced directly from pgplots and the option to produce `ps` and `eps` were instead not documented.

[skip ci] fix and expand file_device and file_extension documentation

---

binary/other/mod_other_tsync.f90
binary/private/binary_ce.f90
binary/private/binary_ctrls_io.f90
binary/private/binary_edot.f90
binary/private/binary_evolve.f90
binary/private/binary_history.f90
binary/private/binary_history_specs.f90
binary/private/binary_jdot.f90
binary/private/binary_job_ctrls_io.f90
binary/private/binary_mdot.f90
binary/private/binary_photos.f90
binary/private/binary_tides.f90
binary/private/binary_timestep.f90
binary/private/pgbinary_ctrls_io.f90
binary/private/pgbinary_full.f90
binary/private/pgbinary_hist_track.f90
binary/private/pgbinary_history_panels.f90
binary/private/pgbinary_star.f90
binary/private/pgbinary_summary_history.f90
binary/private/pgbinary_support.f90
binary/private/run_binary_support.f90
eos/eosDT_builder/src/create_eos_files.f
eos/eosDT_builder/src/eos5_xtrin_h-he.f
eos/eosDT_builder/src/opal_core.f
eos/test/src/sample_eos.f90
sample/src/sample.f90

cleaning up unused variables and some other compiler warnings in `binary`
changed a `dP` to `d_P` to avoid possible conflict with `dp` (since Fortran is case-insensitive)
Goal is that we will add more (best-practice) compile flags to avoid future bugs, but first I need to clean up warnings before committing the flags because there are a lot.

(minor) cleanup warnings in binary

---

net/private/net_burn_const_p.f90
net/test/src/mod_one_zone_burn.f90

Fixes #726 
Set a dummy value for `rpar(r_burn_const_P_rho)` right before this line:
https://github.com/MESAHub/mesa/blob/e29ed74db65f919404919714f058f6ea18cde072/net/private/net_burn_const_p.f90#L198
so it is initialized. The code will calculate the right value later, but prior to that calculation the code (for some reason) has a function that takes the log of this value, so it has to be initialized:
https://github.com/MESAHub/mesa/blob/e29ed74db65f919404919714f058f6ea18cde072/net/test/src/mod_one_zone_burn.f90#L1026

fix uninitialized memory in net_burn_const_p.f90

---

gyre/make/makefile_full

Aside from having to skip tests in many modules, building with `USE_CRMATH = NO`  in `utils/makefile_header` currently fails on GYRE because it's own `CRMATH` make variable defaults to `yes` and it tries to build with CRMATH.
This PR adds a block to export the appropriate value of `CRMATH` in GYRE's makefile, as is already done for `USE_SHARED`/`SHARED`.

Export makefile_header's USE_CRMATH to GYRE's CRMATH

---

docs/source/changelog.rst
star/defaults/controls.defaults
star/private/atm_support.f90
star/private/brunt.f90
star/private/eos_support.f90
star/private/eps_grav.f90
star/private/hydro_vars.f90
star/private/micro.f90
star/private/rsp.f90
star/private/rsp_step.f90
star/private/star_profile_def.f90
star/private/struct_burn_mix.f90
star/private/timestep.f90

The user flag `report_ierr = .true.` is used as a debugging tool to report diagnostics on internal errors in Mesa but not stop the code. Flipping the switch to true should not change the outcome of the simulation. Therefore, we should not call `mesa_error()` inside `if(report_ierr == .true.)` if statements. Either always just halt the code, or use guards like `if(stop_for_bad_nums == .true.)`. 
There are just a handful of cases in the code where this pattern was not followed. This is dangerous because it can cause non-reproducible results when someone is trying to debug their run switches `report_ierr = .true.` on. Particularly in simulations that chain more than one inlist. For example, running `./run_all` for the `20M_pre_ms_to_core_collapse` test problem with `report_ierr = .true.` was …

Do not guard calls mesa_error() with report_ierr

---

turb/plotter/inlist_plotter
turb/plotter/src/turb_plotter.f90
turb/private/kh_instability.f90
turb/private/parasite_model.f90
turb/private/thermohaline.f90
turb/public/turb.f90

The FRG24 model for MHD thermohaline mixing, as currently implemented in the `thermohaline_hackathon` feature branch, is very slow (as pointed out by @evbauer in https://github.com/MESAHub/mesa/commit/d453d85031523d23698559e878bce5ea19de5001 in the context of #605). [I've TeXed up some notes](https://github.com/MESAHub/mesa/files/14658133/FRG24_MESA_speedup_summary.pdf) (TL;DR on page 2) on different ways to speed up the model---some with zero loss in accuracy, some with negligible loss in accuracy, and some with a loss in accuracy that is a factor of a few (but still more accurate than HG19 or the other models currently implemented). This draft PR covers these different speedups. Broadly speaking, they involve a change of basis that block-diagonalizes the matrix we're dealing with, …

Thermohaline hackathon: speeding up FRG24 implementation

---

astero/private/astero_support.f90

The surface correction loops over the modes currently work by always deriving the radial correction and then proceeding onto the non-radial corrections if `radial_only` is `.false.`. This PR consolidates the radial and non-radial loops by using `radial_only` to decide whether to loop over *ℓ* up to 0 (if `.true.`) or 3 (if `.false.`).
I also cleared out trailing whitespace in that file while I was at it.
The `astero` test `surface_effects` passed locally.

Refactor surface corrections to re-use same loop regardless of `radial_only`

---

binary/private/binary_history.f90
binary/private/binary_history_specs.f90
binary/private/pgbinary_summary.f90
binary/private/run_binary_support.f90

Akin to `star/history.f90,` this stop the warning that user-defined columns are not being found when fetching data for `pgbinary`

Small binary_history_fix

---

star/private/adjust_mass.f90

There's a subtle bug in the adjust_mass/adjust_J_lost routine.
When the star is hardly losing mass (say `s% star_mdot < -1d-99`, which is possible when eg using "Kolb" mass transfer without winds), the `mass_lost` in the routine still reads `0d0` to floating point precision, and `s% adjust_J_q` is untouched at `0d0`
Later, in `timestep.f90`, the check is whether `s% mstar_dot < 0d0`, which it is, it's `-1d-99`, and then any hard limit is always hit, causing infinite retries.
this is a simple fix to this bug.

fix bug in adjust_mass.f90

---

binary/defaults/binary_history_columns.list
binary/defaults/pgbinary.defaults
binary/private/binary_history.f90
binary/private/binary_private_def.f90

Small QOL improvement for binary runs.
In binary simulations, the mass ratio is important enough to have a history column available out of the box in mesa (and it required for plotting with `pgbinary`).
I understand the definition of `q` is not universal, some fields use `m1/m2`, others `m2/m1` (I chose the latter, typically the initially less massive over the initially more mass star). Hence I also implemented `min(m2/m1, m1/m2)` as an "observational" mass ratio.

Introduce mass ratio

---

star/defaults/controls.defaults
star/defaults/profile_columns.list
star/private/alloc.f90
star/private/ctrls_io.f90
star/private/hydro_temperature.f90
star/private/profile_getval.f90
star/private/read_model.f90
star/private/star_profile_def.f90
star_data/private/star_controls.inc
star_data/public/star_data_step_work.inc

This PR ports the flux-limiter prescription from Levermore & Pomraning (1981), originally available in MESA r9793, to the latest version. It addresses the following:
- Models radiative transport in the transition from an optically thick to optically thin medium (i.e., from diffusion to free-streaming).
- Prevents photons from escaping at superluminal velocities in the optically thin regime.
The code introduces the following boolean control:
`use_flux_limiting_with_dPrad_dm_form`
When set to .true. and use_dPrad_dm_form_of_T_gradient_eqn = .true., it applies the flux-limiter prescription to compute the radiative pressure gradient in terms of the flux-limiter flxLambda as:
`flxR = 4 * pi * r^2 * abs(dT^4/dm) / kap`
`flxLambda = (6 + 3*flxR) / (6 + 3*flxR + flxR^2)`
Then, the expected …

Porting the flux-limiter prescription from r9793 to the latest MESA version

---

star/defaults/controls.defaults
star/job/run_star_support.f90
star/private/ctrls_io.f90
star/private/micro.f90
star/private/turb_support.f90
star_data/private/star_controls.inc
turb/private/mlt.f90
turb/public/turb.f90
turb/test/src/test_turb.f90

- Limiting convection velocities
As mentioned in #776, the control `max_conv_vel_div_csound ` is mentioned in the documentation but not used. I added support for this control to limit convection velocities for non-TDC MLT options. The main motivation for using this control relies on the assumptions on MLT prescriptions, as the ones from Cox and Mihalas, are not valid for supersonic convection velocities. 
- Introducing opacity floor
As well I add in this patch the control `opacity_min` to be able to have an opacity floor. The motivation for this control comes from the underestimation of line opacities from expanding material by the Ferguson et al. (2005) tables (see section 2.2 in [Morozova et al. (2015)](https://iopscience.iop.org/article/10.1088/0004-637X/814/1/63/meta) for a more …

Adding support to max_conv_vel_div_csound (non-TDC MLT options) and adding opacity_min control

---

docs/source/changelog.rst
star/defaults/controls.defaults
star/private/ctrls_io.f90
star/private/report.f90
star/private/star_utils.f90
star_data/private/star_controls.inc

Resolving https://github.com/MESAHub/mesa/issues/467 raised by @earlbellinger, by adopting @warrickball's suggestion. I introduced a logical control that allows users to choose which method they'd like to use for calculating delta_Pg. The default will now be ``delta_Pg_traditional = .true.``.
I attempted to document the controls and included a changelog. As I am not an asteroseismologist, I'd appreciate someone double checking my explanations.
If this passes testing, we can merge.

adjust delta_Pg

---

star/test_suite/20M_z2m2_high_rotation/inlist_to_end_core_he_burn
star/test_suite/ccsn_IIp/inlist_common
star/test_suite/do1_test_source

These two tests had Skye turned off, apparently from the era when Skye was still under development. The tests pass fine without that toggle, so we should get rid of the lines turning off Skye.

Get rid of legacy EOS settings for some massive star test cases

---

binary/private/binary_photos.f90
binary/private/run_binary_support.f90
binary/public/binary_data.inc
binary/test/src/test_binary.f90
docs/source/changelog.rst

implicit save attribute can be a source of bugs, especially for restart

remove implicit save attribute to binary variables

---

astero/private/adipls_support.f90
eos/eosCMS_builder/src/cms_mixing.f90
eos/eosDT_builder/src/helm_opal_scvh_driver.f90
eos/eosDT_builder/src/scvh_core.f90
num/test/src/bari_beam.f90

Sometimes constants get re-defined (to slightly different values) in parts of the code.  Making things consistent by calling the values from the `const` module.

use consistent values for constants

---

const/public/const_def.f90

Test program to check
```fortran
program main
use iso_fortran_env, only: real32, real64, real128
implicit none
integer, parameter :: my_real32 = selected_real_kind(p=5)
integer, parameter :: my_real64 = selected_real_kind(p=15)
integer, parameter :: my_real128 = selected_real_kind(p=30)
write (*,*) "p = 5 ", real32, my_real32
write (*,*) "p = 15", real64, my_real64
write (*,*) "p = 30", real128, my_real128
end program main
```

const: fix incorrect comments on real precision kinds

---

star/private/ctrls_io.f90

During #471, when cleaning up the control namelist for deprecated items, I mistakenly removed two timestep options from the namelist. Here I reintroduce them.

Restore high_T timestep namelist options

---

docs/source/changelog.rst
star/private/hydro_vars.f90
star/private/rotation_mix_info.f90
star/private/star_utils.f90
star/public/star_lib.f90

Exposing smoothing and kelvin-helmholtz timescale to users to be usable in custom `run_stars_extras`

exposing some star_utils functions to user

---

docs/source/installation.rst

This is a gotcha when installing MESA on a brand-new machine missing the SDK library, users can find out going through the SDK FAQ page, but this adds attrition. This warning should help pointing them in the right direction.

[skip ci] add warning for MESASDK prerequisites

---

astero/test_suite/example_astero/inlist_astero_search_controls
docs/source/changelog.rst
star/defaults/controls.defaults
star/test_suite/20M_z2m2_high_rotation/inlist_to_end_core_he_burn
star/test_suite/extended_convective_penetration/inlist_extended_convective_penetration
star/test_suite/twin_studies/inlist_to_end_core_he_burn

See https://iopscience.iop.org/article/10.3847/2515-5172/adf06d. I am in favor of lowering the default overshoot_D_min if this pr passes testing with no issues.

lower overshoot_D_min

---

gyre/build_and_test
gyre/build_and_test_parallel
gyre/gyre-8.0.tar.gz
gyre/gyre-8.1.tar.gz

Updates GYRE to [v8.1](https://github.com/rhdtownsend/gyre/releases/tag/v8.1), released 11 Sep 2025.
Follows on from previous update to v8.0 in #807.
Tests are [passing](https://testhub.mesastar.org/gyre-8.1/commits/44b1b39), following fixes to `1.4_ms_op_mono` (in da57bc6fc50733418a3c6169677f527e861dec23) and `make_co_wd` (in 10fd9e9f1e6f2e3f5322eb36b65a72237e4d6a88) on `main`.

Update GYRE to 8.1
