docs/source/developing/test_suite.rst
=> [ci skip] Documents setting up a new machine with MESA TestHub

docs/source/test_suite/ppisn.rst, star/private/history.f90, star/private/star_utils.f90, star/public/star_lib.f90, star/test_suite/ppisn/inlist_ppisn, star/test_suite/ppisn/src/run_star_extras.f90, star/test_suite/ppisn/standard_he_dep.mod
May not be all of them yet
Collecting them here so we can squash the commits when they are all fixed
=> Some FPE fixes for ppisn

star/job/run_star_support.f90
Instead of max_model_number / test_suite_res_factor, let's divide by res_factor twice
=> [ci converge] increase max model number

num/make/makefile_base, num/private/mod_integrate.f90, num/public/num_def.f, num/public/num_lib.f, num/test/make/makefile_base, num/test/src/test_integrate.f, num/test/src/test_num.f, num/test/test_output
This is based on simpsons 3/8 rule but runs with adaptive step sizes
with both a relative or absolute tolerance control
=> Add a numerical integrator

binary/private/run_binary_support.f90
Also, when doing wind mass transfer the donor might be the one accreting, so evolve the "accretor" first is needed in that case. This did not trigger correctly.
=> simplified logic for determining which star to evolve first

controls.defaults, ctrls_io.f90, cubic_interpolator.f90, diffusion_procs.f90, diffusion_support.f90, element_diffusion.f90, kap_lib.f90, makefile_base, micro.f90, op_eval_mombarg.f, op_load_master.f, star_controls.inc
Merging branch from Joey's fork onto a MESAHub branch for testing. Once it passes testing, we can merge that branch into main.
=> Op mono and radlev

star/private/evolve.f90, star/private/overshoot.f90, star/private/turb_support.f90
Merge updates to `superad_reduction` method, plus fix for overshoot issue (https://github.com/MESAHub/mesa/issues/400).
=> superad_reduction updates

star/private/pulse_fgong.f90
Closes #352 by implementing the appropriate derivatives of Γ₁ in FGONG output. Derivatives with respect to P and ρ are derived combining other EOS output. The derivative with respect to Y is computed using finite differences. @earlbellinger and I have cross-checked that one Sun-like model gives nearly identical results to the program he currently uses.
In the long run, we probably want to move the derivative calculation into `pulse_utils` or somewhere so the data is also easily available as a profile column. But this at least works so we can start experimenting with it.
=> Implement derivatives of Γ₁ in FGONG format pulsation output

adipls/build_and_test, adipls/build_and_test_parallel, adipls/make/makefile, astero/make/makefile_base, astero/makefile, astero/private/adipls_support.f90, astero/private/adipls_support_procs_stub.f90, astero/private/adipls_support_stub.f90, astero/private/astero_run_support.f90, astero/private/astero_support.f90, astero/public/astero_lib.f90, astero/test_suite/astero_adipls/src/run_star_extras.f90, docs/source/changelog.rst, utils/makefile_header, utils/makefile_header_non_mesasdk
=> Add build option to disable building adipls

binary/private/binary_evolve.f90, binary/private/binary_history.f90, binary/private/run_binary_support.f90, binary/test_suite/double_bh/src/run_binary_extras.f90, binary/test_suite/jdot_ls_check/src/run_star_extras.f90, const/public/const_def.f90, star/private/do_one_utils.f90, star/private/evolve.f90, star/private/history.f90, star/private/pgstar_history_panels.f90, star/private/pgstar_support.f90, star/private/profile_getval.f90, star/private/report.f90, star/test_suite/ccsn_IIp/src/run_star_extras.f90, stella/res/stella_extras.f90
=> added const secday, which is useful for binary stuff

binary/private/binary_evolve.f90, binary/private/binary_timestep.f90, star/private/history.f90, star/test_suite/make_env/src/run_star_extras.f90, star/test_suite/starspots/src/run_star_extras.f90
Start trying to fix binaries fpe's
=> Fixing fpe's in binary

eos/defaults/eos.defaults, eos/private/eos_ctrls_io.f90, eos/public/eos_def.f90, kap/defaults/kap.defaults, kap/private/kap_ctrls_io.f90, kap/public/kap_def.f90
=> Add ability to set user controls in eos/kap inlists

star/defaults/controls.defaults, star/make/makefile_base, star/other/other_close_gaps.f90, star/private/ctrls_io.f90, star/private/mix_info.f90, star_data/private/star_controls.inc, star_data/public/star_data_def.inc, star_data/public/star_data_procedures.inc
Adding a hook for the "close_gaps" routine in star/private/mix_info.f90.  Following @rjfarmer's[ suggestions](https://lists.mesastar.org/pipermail/mesa-users/2022-November/014151.html) (thanks!)
=> Add other_close_gaps hook

docs/source/known_bugs.rst, star/test_suite/ccsn_IIp/.gitignore, star/test_suite/ccsn_IIp/inlist_common, star/test_suite/ccsn_IIp/inlist_edep, star/test_suite/ccsn_IIp/inlist_end_infall, star/test_suite/ccsn_IIp/inlist_infall, star/test_suite/ccsn_IIp/inlist_shock_part2, star/test_suite/ccsn_IIp/inlist_shock_part4, star/test_suite/ccsn_IIp/inlist_shock_part5, star/test_suite/ccsn_IIp/rn, star/test_suite/ccsn_IIp/src/run_star_extras.f90, star/test_suite/ccsn_IIp/standard_shock_part2.mod, star/test_suite/ccsn_IIp/standard_shock_part3.mod
Alot of the code in the run_star_extras isn't even used as it was part of inlist_shock_part6 (which did post shock breakout evolution) which hasn't existed for 2 years. So lets remove it.
Also lets give the many extra controls useful names (which also revealed several controls that overlapped in index).
Before merging remake the standard mods to add back the missing RTI
Photo handling has been updated to the newer testhub way of reading and writing photos.
Tagging Jared  @aurimontem
Still working on adding a check for RTI mixing
=> Cleanup ccsn_IIp

binary/defaults/pgbinary.defaults, binary/private/pgbinary_ctrls_io.f90, binary/private/pgbinary_grid.f90, binary/private/pgbinary_orbit.f90, binary/private/pgbinary_star.f90, binary/public/pgbinary_controls.inc, binary/test_suite/evolve_both_stars/inlist_pgbinary, docs/source/_ext/defaults2rst.py, docs/source/changelog.rst, docs/source/doc_archive/defaults2rst.sh, docs/source/doc_archive/defaultsParser.rb, docs/source/reference.rst, docs/source/reference/pgbinary.rst, star/defaults/pgstar.defaults
added documentation about pgbinary
=> pgbinary docs

star/job/run_star_support.f90
=> Fix logic of initial Temperature guess for eosDE entropy relaxation

.github/workflows/build-linux.yml
testing a fix for recent github action build failures
=> [ci skip] try fix for aspnetcore build failures

star/other/pgstar_decorator.f90
clarify other hook in response to https://github.com/MESAHub/mesa/issues/579
=> [ci skip] Update pgstar_decorator to comment about pg struct

neu/private/mod_neu.f90
this reduces the number of expensive intrinsics needed
=> replace sin/cos with multiangle formula in neutrino cooling

net/private/net_burn_const_density.f90, star/defaults/controls.defaults, star/defaults/controls_dev.defaults
See https://github.com/MESAHub/mesa/issues/599. I've moved the control for toggling the const density solver into developer defaults until the const density solver is debugged or removed.
=> partial-Fix const density burn solver

binary/defaults/binary_controls.defaults, binary/private/binary_ctrls_io.f90, binary/public/binary_controls.inc, binary/public/binary_def.f90
Follow up to #608 to merge after testing.
=> added x_{type}_ctrl inlist controls to binary controls (Part II)

docs/source/changelog.rst, star/defaults/controls.defaults, star/private/ctrls_io.f90, star/private/hydro_energy.f90, star/private/hydro_momentum.f90, star/private/report.f90, star/test_suite/make_pre_ccsn_13bvn/inlist_to_cc, star_data/private/star_controls.inc
@mathren's fix for the infall velocity. See https://github.com/MESAHub/mesa/pull/627#issue-2161886494 and https://github.com/MESAHub/mesa/issues/626.
=> fix infall velocity

docs/source/faq.rst, docs/source/using_mesa/extending_mesa.rst
Stumbled upon a few rotten links in the documentation FAQ and fixed them.
=> fix links to SDK website

scripts/shmesa/shmesa
=> shmesa fix for issue #661

docs/source/using_mesa/building_inlists.rst, star/test_suite/12M_pre_ms_to_core_collapse/inlist_common, star/test_suite/20M_pre_ms_to_core_collapse/inlist_common, star/test_suite/hb_2M/README.rst, star/test_suite/zams_to_cc_80/inlist_common
@xingyzt has found and fixed some typos in the docs, and a typo in the test_suite. we can use this pull request to merge in some extra doc fixes as well.
=> Typo fixes xingyzt

docs/requirements.txt
bug patch for https://github.com/MESAHub/mesa/pull/681
=> removing redundant requirement in docs to build on readthedocs

.readthedocs.yaml, docs/requirements.txt, docs/source/conf.py
This is to check if this triggers readthedocs' version warning add on, which I've enabled at https://app.readthedocs.org/projects/mesa-doc/
=> Updating readthedocs sphinx python and extension versions

docs/source/conf.py
=> readthedocs fix for upcoming depricated features

mtx/private/bcyclic.f90, mtx/public/mtx_dble_decsol.dek
some simple warning cleanups
I merged Vincent's PR into this branch to test before merging into main:
https://github.com/MESAHub/mesa/pull/710
=> Vincent's vv/mtx simple warnings

utils/private/utils_c_system.c, utils/private/utils_c_system.h
Testing @VincentVanlaer 's PR https://github.com/MESAHub/mesa/pull/704 in a branch here before committing to main
=> Vincent's vv/utils warn cleanup

num/public/num_lib.f
Solves issue # 741:  https://github.com/MESAHub/mesa/issues/741
=> Fix what gets exposed in num

star/private/do_one_utils.f90, star/test_suite/12M_pre_ms_to_core_collapse/inlist_pgstar, star/test_suite/20M_pre_ms_to_core_collapse/inlist_pgstar, star/test_suite/20M_z2m2_high_rotation/README.rst, star/test_suite/20M_z2m2_high_rotation/inlist_pgstar, star/test_suite/make_o_ne_wd/inlist_pgstar, star/test_suite/make_pre_ccsn_13bvn/inlist_pgstar, star/test_suite/ns_c/inlist_pgstar, star/test_suite/pisn/inlist_pgstar, star/test_suite/split_burn_big_net/inlist_pgstar, star/test_suite/twin_studies/inlist_pgstar, star/test_suite/zams_to_cc_80/inlist_pgstar
I noticed I missed a few spots when changing lg_Lnuc to lg_Lnuc_tot. let me know if it's fine and i'll merge.
=> fix places where lg_Lnuc should be lg_Lnuc_tot

binary/private/pgbinary_full.f90, binary/public/binary_pgbinary.f90
Addresses #843 found during the MESA 2025 summer school.
=> Add the orbit window device number
